services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: epstein
      POSTGRES_USER: epstein
      POSTGRES_PASSWORD: epstein
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: changemechangeme
      MEILI_ENV: production
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch:/meili_data
